source 'https://rubygems.org'

gem "jekyll", "~> 4.3" # installed by `gem jekyll`
gem "webrick"

gem "just-the-docs"

gem "jekyll-default-layout"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-mentions"
gem "jekyll-optional-front-matter"
gem "jekyll-paginate"
gem "jekyll-readme-index"
gem "jekyll-redirect-from"
gem "jekyll-relative-links"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-titles-from-headings"
gem "jemoji"
